spring.application.name=datashare

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:datashare}
spring.datasource.username=${DB_USER:datashare}
spring.datasource.password=${DB_PASSWORD:datashare}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

aws.s3.endpoint=${S3_ENDPOINT:}
aws.s3.region=${S3_REGION:us-east-1}
aws.s3.access-key=${S3_ACCESS_KEY:}
aws.s3.secret-key=${S3_SECRET_KEY:}
aws.s3.path-style-access=${S3_PATH_STYLE_ACCESS:false}

#JWT_SECRET_KEY=${JWT_SECRET_KEY:secret}
#JWT_EXPIRATION_MS=${JWT_EXPIRATION_MS:3600000}

JWT_SECRET_KEY=Y2zDqV9zZWNyw6h0ZV9wb3VyX3Rva2VuX2p3dF9hcHBfb2NfcDJfMjAyNg==

JWT_EXPIRATION_MS=86400000